[package]
name = "scholar-search-pdf-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tesseract-plumbing = "0.11.0"
leptonica-plumbing = "1.3.0"


